# Generated by Django 5.0.6 on 2024-06-25 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_post_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
        migrations.AddField(
            model_name='post',
            name='Post_image',
            field=models.ImageField(default='How-to-Setup-ReactJS-with-Django_Jf3oK5G.png', upload_to=''),
        ),
        migrations.AddField(
            model_name='post',
            name='User_image',
            field=models.ImageField(default='How-to-Setup-ReactJS-with-Django_Jf3oK5G.png', upload_to=''),
        ),
        migrations.AddField(
            model_name='post',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
