# Generated by Django 5.0.6 on 2024-06-25 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_post_image_post_post_image_post_user_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='User_image',
            field=models.ImageField(default='How-to-Setup-ReactJS-with-Django_Jf3oK5G.png', upload_to=''),
        ),
    ]
