# Generated by Django 5.0.6 on 2024-07-28 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_friend_request_friends'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(default='username', max_length=70, unique=True),
        ),
    ]
