# Generated by Django 5.0.6 on 2024-08-04 15:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_chartdata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chartdata',
            name='month',
        ),
        migrations.AddField(
            model_name='chartdata',
            name='date',
            field=models.DateField(default='2000-01-01'),
        ),
        migrations.AlterField(
            model_name='chartdata',
            name='user',
            field=models.ForeignKey(blank='false', default='username', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
