# Generated by Django 5.0.6 on 2024-08-04 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_remove_chartdata_month_chartdata_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chartdata',
            name='date',
            field=models.DateField(default='2000-01-01'),
        ),
    ]
