# Generated by Django 5.0.6 on 2024-08-04 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_chartdata_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chartdata',
            name='date',
            field=models.DateField(blank='true', null='true'),
        ),
    ]
