# Generated by Django 5.0.6 on 2024-08-04 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_rename_date_chartdata_month'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chartdata',
            name='month',
            field=models.DateTimeField(blank='true', null='true'),
        ),
    ]
