# Generated by Django 5.0.6 on 2024-08-04 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_chartdata_month'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChartData',
        ),
    ]
