# Generated by Django 5.0.6 on 2024-08-06 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_chartdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='job',
            field=models.CharField(default='', max_length=80, null=True),
        ),
    ]
