# Generated by Django 5.0.6 on 2024-08-06 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_customuser_job'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='title',
            new_name='type',
        ),
    ]
