# Generated by Django 5.0.6 on 2024-11-01 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_rename_title_post_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='Post_image',
            field=models.ImageField(default='How-to-Setup-ReactJS-with-Django_Jf3oK5G.png', upload_to='media/'),
        ),
    ]
